// <auto-generated />
namespace hitchbot_secure_api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddBucketList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBucketList));
        
        string IMigrationMetadata.Id
        {
            get { return "201506301430112_AddBucketList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
