<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="DynamicMap.aspx.cs" Inherits="hitchbotAPI.ApproveImagesPages.DynamicMap" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
      html, body, #map-canvas { height: 100%; margin: 0; padding: 0;}
    </style>
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCV-d9jbUEWesRS6LRsWCWZpKZdOmXCUWA">
    </script>
    <asp:Literal runat="server" id="jsDataLocation" EnableViewState="false" />
    <script type="text/javascript">
      function initialize() {
        var mapOptions = {
          center: { lat: 48.3822, lng: -89.2461},
          zoom: 4
        };
        var map = new google.maps.Map(document.getElementById('map-canvas'),
            mapOptions);
         
          //generated by the server every set period of time!
        AddPolyFill(map);
        AddStartMarker(map);
        AddEndMarker(map);
        AddHbMarker(map);
        AddInfoWindow(map);
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
</head>
<body>
    <div id="map-canvas"></div>
    <form id="form1" runat="server"></form>
</body>
</html>
